name: GitLab Provider Lint
on: [push,pull_request]

# Not running this action with a matrix, because the linter creates a code annotation for each issue,
# and there would be a lot of duplicate annotations if using a matrix.
jobs:
  gitlabproviderlint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code repository source code
        uses: actions/checkout@v2

      # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions
      - name: Set build variables
        run: |
          echo "::set-env name=GO_FLAGS::-mod=vendor"
          echo "::set-env name=GO111MODULE::on"

      - name: Run gitlabproviderlint
        run: |
          make gitlabproviderlint
